Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> print(4)
4
>>> type(3.2)
<class 'float'>
>>> type('17')
<class 'str'>
>>> n = 17
>>> pi = 3.1415926535897931
>>> print(n)
17
>>> print(pi)
3.141592653589793
>>> print(1)
1
>>> x = 2
>>> perint(x)
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    perint(x)
NameError: name 'perint' is not defined
>>> print(x)
2
>>> print(1);
1
>>> 20+32
52
>>> hour-1
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    hour-1
NameError: name 'hour' is not defined
>>> 5**2
25
>>> hour*60+minute
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    hour*60+minute
NameError: name 'hour' is not defined
>>> minute/60
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    minute/60
NameError: name 'minute' is not defined
>>> (5+9)*(15-7)
112
>>> minute = 59
>>> minute/60
0.9833333333333333
>>> minute//60
0
>>> 17
17
>>> x
2
>>> 2**3-1
7
>>> 2**2
4
>>> 1**1
1
>>> 1**4
1
>>> 5**3
125
>>> 2**1+1
3
>>> 2**2
4
>>> 2**2+1
5
>>> 2**(2+1)
8
>>> 25//5
5
>>> 125//5
25
>>> 144//2
72
>>> first = 10
>>> second = 15
>>> print(first+second)
25
>>> first = '100'
>>> second = '150'
>>> print(first + second)
100150
>>> first(first * second)
Traceback (most recent call last):
  File "<pyshell#42>", line 1, in <module>
    first(first * second)
TypeError: can't multiply sequence by non-int of type 'str'
>>> first = 'Krāts'
>>> second = 3
>>> second = 2000
>>> print(first * second)
KrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrātsKrāts
>>> inp = input()
